services:
    zoffline:
        image: ghcr.io/fatsbrown/zoffline:latest
        container_name: zoffline
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - ./storage/:/usr/src/app/zwift-offline/storage
        networks:
            zwiftnet:
                ipv4_address: 192.168.99.2
        restart: unless-stopped

networks:
    zwiftnet:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.99.0/24
